'use client';
import { useMemo, useState } from 'react';
type Intel={id:string;title:string;type:'Document'|'Audio Log'|'Artifact'|'Transmission';area:string;note:string;x:number;y:number};
const intel:Intel[]=[
 {id:'qmf-01',title:'Quantum Mechanical Failure',type:'Document',area:'Motel — Room 202',note:'Pinned beside the overturned bedside lamp.',x:28,y:29},
 {id:'qmf-02',title:'The Janus File',type:'Document',area:'Olly’s Comics',note:'Behind the counter, beneath a stack of newspapers.',x:53,y:42},
 {id:'qmf-03',title:'Echoes from Requiem',type:'Audio Log',area:'Riverside',note:'Listen for the radio beside the flooded storefront.',x:72,y:31},
 {id:'qmf-04',title:'Aetheric Residue Sample',type:'Artifact',area:'Church',note:'Resting on a shelf in the back office.',x:66,y:68},
 {id:'qmf-05',title:'Project Janus Broadcast',type:'Transmission',area:'Savings & Loan',note:'A transmitter sits in the vault corridor.',x:38,y:75},
];
const filters=['All intel','Documents','Audio logs','Artifacts','Uncollected'];
export default function Home(){
 const[activeFilter,setActiveFilter]=useState('All intel');const[selected,setSelected]=useState<Intel>(intel[0]);const[secured,setSecured]=useState<string[]>(['qmf-03']);const[showFile,setShowFile]=useState(true);
 const visible=useMemo(()=>intel.filter(i=>{if(activeFilter==='All intel')return true;if(activeFilter==='Uncollected')return!secured.includes(i.id);return i.type===({Documents:'Document','Audio logs':'Audio Log',Artifacts:'Artifact'}as Record<string,Intel['type']>)[activeFilter]}),[activeFilter,secured]);
 const isSecured=secured.includes(selected.id), progress=Math.round(secured.length/intel.length*100);const toggle=()=>setSecured(s=>s.includes(selected.id)?s.filter(id=>id!==selected.id):[...s,selected.id]);
 return <main className="archive-shell"><header className="topbar"><a className="brand" href="/"><span className="brand-mark">DA</span><span>DARK AETHER<br/><b>ARCHIVE</b></span></a><nav><a className="active" href="/">Dashboard</a><a href="/maps">Maps</a><a href="/intel">Intel archive</a><a href="/timeline">Timeline</a><a href="/signals">Signals archive</a></nav><button className="profile-button">SIGN IN <span>↗</span></button></header>
 <section className="home-dashboard" id="top"><aside className="dashboard-rail"><span className="rail-title">CALL OF DUTY INTEL</span><a className="rail-current" href="#top">❯ Welcome</a><a href="#top">❯ Dashboard</a><span className="rail-heading">INTEL</span><a href="#maps">❯ Intel Completionists</a><a href="#maps">❯ Black Ops 6 Intel</a><a href="#maps">❯ MWZ Intel</a><a href="#maps">❯ Vanguard Intel</a><a href="/intel/cold-war">❯ Cold War Intel</a><a href="#signals">❯ Chaos Radios</a><a href="#signals">❯ Aether Radios</a></aside><section className="dashboard-main"><span className="eyebrow">DARK AETHER ZOMBIES INTEL INDEX</span><h1>Welcome, <em>operative.</em></h1><p className="dashboard-lede">A field index for every recovered document, transmission, artifact, and audio log — built to track your collection across the Dark Aether story.</p><div className="dashboard-status"><span>INTEL COMPLETIONISTS</span><b>YOUR ARCHIVE IS <i>{progress}% SECURED</i></b><div className="dashboard-progress"><i style={{width:`${progress}%`}}/></div><small>{secured.length} RECOVERED / {intel.length} AVAILABLE IN CURRENT OPERATION</small></div><div className="game-cards"><a href="#maps"><span>BLACK OPS 6</span><strong>Liberty Falls</strong><b>{secured.length}/{intel.length}</b><i style={{width:`${progress}%`}}/></a><a href="#maps"><span>MODERN WARFARE ZOMBIES</span><strong>Intel Index</strong><b>0/578</b><i/></a><a href="#maps"><span>VANGUARD</span><strong>Intel Index</strong><b>0/74</b><i/></a><a href="/intel/cold-war"><span>BLACK OPS COLD WAR</span><strong>Intel Index</strong><b>0/115</b><i/></a></div><div className="dashboard-actions"><a href="#maps">OPEN MAP INDEX →</a><a href="#timeline">VIEW STORYLINE TIMELINE →</a></div></section><aside className="dashboard-links"><span>OTHER ARCHIVES</span><a href="#maps">Zombies Sheets <b>→</b></a><a href="#maps">Easter Egg Checklists <b>→</b></a><a href="#signals">Camo Index <b>→</b></a><div className="credits"><span>CREDITS</span><p>Built as an unofficial community intelligence archive.</p><p>Research must remain sourced and attributable.</p></div></aside></section>
 <section className="command-strip"><div><span className="eyebrow">OPERATIONAL INDEX / LIBERTY FALLS</span><h1>Intel recovery<br/>field terminal</h1></div><div className="total-progress"><span>PERSONAL RECOVERY STATUS</span><strong>{secured.length}<em> / {intel.length}</em></strong><div className="progress"><i style={{width:`${progress}%`}}/></div><small>{progress}% SECURED</small></div><div className="command-actions"><button onClick={()=>setShowFile(true)}>OPEN CASE FILE</button><button className="quiet">⌘ SEARCH</button></div></section>
 <section className="workspace" id="maps"><aside className="intel-sidebar"><div className="side-heading"><span>INTELLIGENCE INVENTORY</span><b>{visible.length} RECORDS</b></div><label className="search"><span>⌕</span><input aria-label="Search intel" placeholder="Search recovered intelligence"/></label><div className="filter-row">{filters.map(f=><button key={f} className={activeFilter===f?'selected':''} onClick={()=>setActiveFilter(f)}>{f}</button>)}</div><div className="record-list">{visible.map((item,i)=><button className={`record ${selected.id===item.id?'current':''}`} key={item.id} onClick={()=>{setSelected(item);setShowFile(true)}}><span className="record-icon">{i+1}</span><span><strong>{item.title}</strong><small>{item.type} · {item.area}</small></span><i className={secured.includes(item.id)?'secured-dot':''}>{secured.includes(item.id)?'✓':'○'}</i></button>)}</div><div className="side-footer"><span>BLACK OPS 6</span><b>LIBERTY FALLS</b><small>QUANTUM MECHANICAL FAILURE</small></div></aside>
 <section className="map-area" aria-label="Liberty Falls interactive intelligence map"><div className="map-grain"/><div className="map-top"><span>LIBERTY FALLS // SECTOR 07</span><span>GRID REF: 39°18′N · 78°10′W</span></div><div className="map-water water-one"/><div className="map-water water-two"/><div className="road road-one"/><div className="road road-two"/><div className="road road-three"/><div className="district district-one">MOTEL<br/><small>202</small></div><div className="district district-two">OLLY’S<br/>COMICS</div><div className="district district-three">RIVERSIDE</div><div className="district district-four">CHURCH</div><div className="district district-five">SAVINGS<br/>&amp; LOAN</div>{visible.map(item=><button aria-label={`View ${item.title}`} className={`map-marker ${item.id===selected.id?'marker-active':''} ${secured.includes(item.id)?'marker-secured':''}`} style={{left:`${item.x}%`,top:`${item.y}%`}} key={item.id} onClick={()=>{setSelected(item);setShowFile(true)}}><span>{secured.includes(item.id)?'✓':'✦'}</span></button>)}<div className="map-legend"><span><i className="legend-document"/> DOCUMENT</span><span><i className="legend-audio"/> AUDIO</span><span><i className="legend-artifact"/> ARTIFACT</span></div><div className="map-controls"><button>+</button><button>−</button><button>⌖</button></div><div className="scan-line"/></section>
 {showFile&&<aside className="case-file"><button className="close-file" onClick={()=>setShowFile(false)}>×</button><div className="folder-tab">BLACK OPS 6 <span>LIBERTY FALLS</span></div><div className="classification">TOP SECRET // DARK AETHER</div><div className="case-number">CASE FILE: LF-QMF-{selected.id.slice(-2).toUpperCase()} <span>REVIEWED 2026.08.24</span></div><div className="paperclip">⌇</div><article className="dossier-paper"><p className="paper-label">RECOVERED INTELLIGENCE / {selected.type.toUpperCase()}</p><h2>{selected.title}</h2><dl><div><dt>LOCATION</dt><dd>{selected.area}</dd></div><div><dt>STATUS</dt><dd>{isSecured?'SECURED':'UNRECOVERED'}</dd></div><div><dt>RELEVANCE</dt><dd>PROJECT JANUS</dd></div></dl><hr/><p className="transcript">A fragmented record recovered from the Liberty Falls containment zone. Its contents point to a failure in the quantum barrier and an operation that was never meant to surface.</p><blockquote>“{selected.note}”</blockquote><p className="redacted">SOURCE REVIEW: ████████████ / REQUIEM ARCHIVE</p></article><button className={`secure-button ${isSecured?'is-secured':''}`} onClick={toggle}>{isSecured?'✓ INTEL SECURED':'MARK AS SECURED'}</button><button className="map-link" onClick={()=>setShowFile(false)}>VIEW LOCATION ON MAP →</button><p className="citation">SOURCES REQUIRED FOR PUBLICATION · VIEW RESEARCH LOG</p></aside>}</section>
 <section className="lower-decks"><article id="timeline"><span className="eyebrow">DARK AETHER // STORYLINE BRIEFING</span><h2>Follow the breach<br/>from Cold War onward.</h2><p>A source-cited chronology connecting maps, operatives, factions, recovered material, and verified story events.</p><button>OPEN TIMELINE →</button></article><article id="signals"><span className="eyebrow">SIGNALS ARCHIVE // ARG EVIDENCE</span><h2>Every cipher leaves<br/>a trace.</h2><p>Pawn Takes Pawn, The Truth Lies, and The Die Is Cast preserved as a dated investigation record.</p><button>ENTER SIGNALS ARCHIVE →</button></article><article className="notice"><span>UNOFFICIAL COMMUNITY ARCHIVE</span><p>Dark Aether Archive is a fan project. Content must be cited, attributable, and never presented as official without evidence.</p><a href="#archive">READ SOURCE POLICY →</a></article></section></main>
}
